### ISSUE TITLE
Ability to differentiate between open-source and proprietary apps.

### ISSUE THREAD

**Issue by ghost** [accrescent/accrescent#634] opened 2024-11-12 21:26 UTC
With the addition of the first proprietary app in Accrescent, Qlango, I think it is important to prioritise a feature that would allow users to differentiate between open-source and proprietary apps. This is to prevent users from unknowingly installing Qlango or other proprietary apps (when they are added) under the false assumption that they are installing open-source apps.

**Comment by Airradda** [comment] 2024-11-12 22:47
I believe this is a duplicate of #622, which was closed as a duplicate of [accrescent/meta#25](https://github.com/accrescent/meta/issues/25).

**Closed as completed** 2024-11-12 22:52 UTC
