### ISSUE TITLE
Richer app metadata

### ISSUE THREAD

**Issue by easrng** [accrescent/accrescent#546] opened 2024-07-21 05:49 UTC
I'd like to see screenshots, a more detailed description, and links to the project/developer's website before I install an app.

**Comment by rusty-snake** [comment] 2024-07-21 05:54
- https://github.com/accrescent/meta/issues/16
- https://github.com/accrescent/meta/issues/14
- https://github.com/accrescent/meta/issues/21

**Comment by lberrymage** [comment] 2024-07-21 06:14
Closing as duplicate of existing issues per the above comment

**Closed as not planned by lberrymage** 2024-07-21 06:14 UTC
