### ISSUE TITLE
Accrescent unable to update itself if originally installed from outside Accrescent

### ISSUE THREAD

**Issue by AtmosphericIgnition** [accrescent/accrescent#529] opened 2024-07-01 21:43 UTC
I have downloaded Accrescent 0.20.0 from GitHub releases using Obtainium. Now that Accrescent 0.21.0 has been released, Accrescent is unable to update itself, as it can see that it was installed from a different source. The button which would usually allow to update is greyed out with text reading "App installed from another source."

![signal-2024-07-01-233336_002](https://github.com/accrescent/accrescent/assets/147227691/0c6419d1-54c8-4cdc-b85c-5d988f32839d)
![signal-2024-07-01-233336_003](https://github.com/accrescent/accrescent/assets/147227691/e0685269-607c-4959-9fbb-36ddbd5b15c7)

**Comment by lberrymage** [comment] 2024-07-02 04:31
This is expected behavior as of 0.20.0, but an option should be added to make Accrescent take over as the installer of record

**Comment by AtmosphericIgnition** [comment] 2024-07-02 12:23
I understand that this is expected for apps installed using Accrescent (since 0.20.0), but the release notes (as far as I understand) make it sound like Accrescent should be able to take ownership of itself, and update itself (even when installed from a different source), but in my case, Accrescent is unable to update itself.

From the 0.20.0 release notes:
"Accrescent now respects other app stores and manual APK installations, no longer attempting to take over updates for apps you installed outside of Accrescent (one exception: Accrescent itself installed manually from an APK)."

Sorry if I'm misunderstanding.

**Comment by PatrykMis** [comment] 2024-07-02 16:11
I think there should be also an option for ability to take ownership for any of the listed apps.

If we clear Accrescent's data or reinstall it, all apps have to be uninstalled and installed to restore Accrescent's ownership.

**Comment by lberrymage** [comment] 2024-07-03 07:33
> I understand that this is expected for apps installed using Accrescent (since 0.20.0), but the release notes (as far as I understand) make it sound like Accrescent should be able to take ownership of itself, and update itself (even when installed from a different source), but in my case, Accrescent is unable to update itself.
> 
> From the 0.20.0 release notes: "Accrescent now respects other app stores and manual APK installations, no longer attempting to take over updates for apps you installed outside of Accrescent (one exception: Accrescent itself installed manually from an APK)."
> 
> Sorry if I'm misunderstanding.

I see how it's worded a little confusingly. It's supposed to mean that Accrescent won't attempt to update any app installed from somewhere other than Accrescent, including Accrescent itself if it was installed from e.g. Obtainium. The only exception is that Accrescent can update itself if it was originally installed from an APK.

**Comment by lberrymage** [comment] 2024-07-03 07:50
I'm going to mark this as closed by https://github.com/accrescent/accrescent/commit/75f48437e363be84c93aad5bb604763cc4dec369 since it should allow Accrescent to update itself, but I've created https://github.com/accrescent/accrescent/issues/534 for the update takeover feature

**Closed as completed by lberrymage** 2024-07-03 07:50 UTC
Labels: enhancement
