### ISSUE TITLE
Auto refresh store on open

### ISSUE THREAD

**Issue by BHydden** [accrescent/accrescent#158] opened 2023-01-15 09:57 UTC
Currently the store doesn't seem to auto refresh. Users are not seeing new apps in the list until after a manual refresh. Perhaps the app list should either refresh each time the store is opened or each time it polls for updates?

**Comment by lberrymage** [comment] 2023-01-15 17:25
Strange. It should refresh on each update check.
https://github.com/accrescent/accrescent/blob/c091e16ca28c34e51285492737df7d98d3e85f85/app/src/main/java/app/accrescent/client/workers/AutoUpdateWorker.kt#L22

**Comment by lberrymage** [comment] 2023-02-24 05:07
I can't reproduce this, and the code appears to be correct. Can you confirm that it doesn't auto refresh for sure?

**Comment by BHydden** [comment] 2023-02-24 06:50
Hard to test since new apps / updates are so infrequent and update in the background, so there are very small windows to test a new app being released but not yet picked up by accrescent 🤔

**Comment by lberrymage** [comment] 2023-10-19 06:11
Closing as resolved by https://github.com/accrescent/accrescent/commit/12e252c4d1c806d557ebddd02eb8a4913ac01c07

**Closed as completed** 2023-10-19 06:11 UTC
Labels: enhancement
